//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Id { get; set; }
        public string SellerId { get; set; }
        public string CategoryId { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public Nullable<int> Stock { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
